version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: myweb-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=myweb_db
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
      ports:
        - "3307:3306"

    webserver:
      image: nginx:alpine
      container_name: myweb-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "1985:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: myweb-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

